### ISSUE TITLE
(.env) C:\Users\Lotus\Desktop\ChatBot_Rasa\.env\Scripts>python -m spacy download en

### ISSUE THREAD

**Issue by Sankalikhitha** [statsmaths/cleanNLP#46]
(.env) C:\Users\Lotus\Desktop\ChatBot_Rasa\.env\Scripts>python -m spacy download en
Traceback (most recent call last):
  File "C:\Python36\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Python36\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Python36\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Lotus\Desktop\ChatBot_Rasa\.env\lib\site-packages\spacy\__init__.py", line 10, in <module>
    from .cli.info import info as cli_info
  File "C:\Users\Lotus\Desktop\ChatBot_Rasa\.env\lib\site-packages\spacy\cli\__init__.py", line 6, in <module>
    from .train import train
  File "C:\Users\Lotus\Desktop\ChatBot_Rasa\.env\lib\site-packages\spacy\cli\train.py", line 12, in <module>
    from ..gold import GoldCorpus, minibatch
  File "strings.pxd", line 23, in init spacy.gold
ImportError: DLL load failed: The specified module could not be found.

After installing spacy model,While downloading the spacy en getting the above error.Please can anyone resolve it.

_Originally posted by @Sankalikhitha in https://github.com/statsmaths/cleanNLP/issues/10#issuecomment-459948208_

**Comment by taylor-arnold** [comment]
This issue has nothing to do with the R package and seems to be purely spacy issue. I would suggest opening an issue on their repository.
